### ISSUE TITLE
Puppet version sanity

### ISSUE THREAD

**Issue by garethr** [gds-operations/puppet-skeleton#4]
Any thoughts on using an omnibus install of Puppet or other mechanism to specify the version in the Vagrantfile when first provisioning?

Lots of interesting/useful prior art. Potentially of use:

https://github.com/patcon/vagrant-puppet-install

Some discussion of where that came from and that some of this is likely to make it's way into vagrant:

https://github.com/schisamo/vagrant-omnibus/issues/18

Omnibus packages for puppet, and a vagrant plugin.

https://github.com/fnichol/omnibus-puppet
https://github.com/schisamo/vagrant-omnibus

**Comment by deanwilson** [comment]
While we would be happy to review the code to implement this change we're not currently planning on implementing it ourself. Thank you for your suggestion.
